config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
    root 'public#bucket_list_index'

    match('/users/:id/get_random_adventure', {:via => :get, :to => 'users#get_random_adventure'})
    match('/adventures/get_random_adventure', {:via => :get, :to => 'adventures#get_random_adventure'})
    match('/adventures/:id/add_comment' , {:via => :post, :to => 'adventures#add_comment'})
    match('/adventures/:id/add_tag' , {:via => :post, :to => 'adventures#add_tag'})
    match('/users/search_users' , {:via => :get, :to => 'users#search_users'})
    match('users/show' , {:via => :get, :to => 'users#show'})
    match('users/show/newPic' , {:via => :get, :to => 'users#newPic'})
    match('users/show/cancel' , {:via => :get, :to => 'users#cancel'})
    match('users/show/addUserPicture' , {:via => :post, :to => 'users#addUserPicture'})
    match('users/:id/followUser' , {:via => :get, :to => 'users#followUser'})
    match('users/:id/unfollowUser' , {:via => :get, :to => 'users#unfollowUser'})
    match('users/show/followPage' , {:via => :get, :to => 'users#followPage'})
    match('users/all', {:via => :get, :to => 'users#index'})
    match('users/:id' , {:via => :get, :to => 'users#view_profile'})
    match('/users/:id/add_adventure' , {:via => :post, :to => 'users#add_adventure'})
    match('/adventures/search_adventures' , {:via => :get, :to => 'adventures#search_adventures'})

    resources :migrations
    resources :pictures
    resources :adventures

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    has_many :adventures, dependent: :destroy

    acts_as_followable
    acts_as_follower

    accepts_nested_attributes_for :adventures,
                                  reject_if: proc { |attributes| attributes['title'].blank? },
                                  allow_destroy: true

    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

         def self.from_omniauth(auth)
           where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
             user.email = auth.info.email
             user.password = Devise.friendly_token[0,20]
             user.first_name = auth.info.name.split(' ').first
             user.last_name = auth.info.name.split(' ').last

            #  assuming the user model has a name
            #  user.image = auth.info.image # assuming the user model has an image
           end
         end
    has_attached_file :image, styles: { small: "64x64", med: "200x200", large: "400x400" }

    validates_attachment :image,
       content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
       size: { in: 0..10.megabytes }

   def image_from_url(url)
       self.image = open(url)
   end

#
#    has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
#    validates_attachment :image, :presence => true,
#      content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
#      size: { in: 0..10.megabytes }

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

# You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :configure_devise_params, if: :devise_controller?
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  
    
  def update
     self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
     if resource.update_with_password(user_params)
       if is_navigational_format?
         flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ? :update_needs_confirmation : :updated
         set_flash_message :notice, flash_key
       end
       sign_in resource_name, resource, :bypass => true
       respond_with resource, :location => after_update_path_for(resource)
     else
       clean_up_passwords resource
       respond_with resource
     end
   end
    
  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_in){ |u| u.permit(:email, :password) }
     devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:first_name, :last_name, :city, :state, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.for(:account_update){ |u| u.permit(:first_name, :last_name, :city, :state, :about, :email, :password, :password_confirmation) }
   end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
#  def configure_account_update_params
#    devise_parameter_sanitizer.for(:account_update) << :attribute
#  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
private
  
  def set_recipe
      @user = User.find(params[:id])
  end


 def user_params
     params.require(:user).permit(:first_name, :last_name, :city, :state, :about, adventures_attributes: [:id, :title, :description, :duedate, :creator, :priority, :completed, :_destroy])
 end
    
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#before_filter :configure_sign_up_params, only: [:create]
#before_filter :configure_account_update_params, only: [:update]
before_action :authenticate_user!

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_in){ |u| u.permit(:email, :password) }
     devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:first_name, :email, :password, :password_confirmation)}
     devise_parameter_sanitizer.for(:account_update){ |u| u.permit(:first_name, :email, :password, :password_confirmation) }
   end

  def index
     @users = User.paginate(:page => params[:page], :per_page => 16)
  end

  def show
    @user = current_user
    render 'show.html.erb'
  end

  def view_profile
    @user = User.find(params[:id])
    render 'show.html.erb'
  end

  def add_adventure
    @user = User.find(params[:id])
    newAdventure = Adventure.new(params[:adventure])
    if newAdventure.valid?
      newAdventure.title.downcase! # ! alters the original
      newAdventure.save
      newAdventure.creator = @user.first_name + ' ' + @user.last_name
      if !params[:image_url].blank?
        newAdventure.image = newAdventure.image_from_url(params[:image_url])
      end
        if params[:image_url].blank? && newAdventure.image.blank?
          newAdventure.image = "https://briancromer.files.wordpress.com/2010/09/ds-print1.jpg"
      end
      @user.adventures << newAdventure
      @user.save
    end
    redirect_to "/users/#{@user.id}"
  end

  def get_random_adventure
      @user = User.find(params[:id])
      @adventure = @user.adventures.sample
      if !@adventure.nil?
            respond_to do |format|
              format.json { render :show, status: :ok, location: @adventure }
            end
      else
          respond_to do |format|
              format.json { render :json => {}, :status => :ok }
          end
      end
  end

  def search_users
    if !params[:creator].nil?
      search_string = params[:creator]
      @user = User.basic_search({first_name: search_string, last_name: search_string}, false).paginate(:page => params[:page], :per_page => 16)
    end
  end

  def newPic
    @user = current_user
  end

  def cancel
  end

  def addUserPicture
    @user = current_user
    if params[:image_cb2] == "3"
      @user.image = @user.image_from_url(params[:image_url2])
    else
      @user.image = params[:user_image]
    end
    @user.save
    redirect_to users_show_path
  end

  def followUser
    @user = User.find(params[:id])
    current_user.follow!(@user)
    redirect_to "/users/#{@user.id}"
  end

  def unfollowUser
    @user = User.find(params[:id])
    current_user.unfollow!(@user)
    redirect_to "/users/#{@user.id}"
  end

    def followPage
      @followers = current_user.followees(User)
      @yourFollowers = current_user.followers(User)
    end


private
  def set_user
    @user = User.find(params[:id])
  end


 def user_params
     params.require(:user).permit(:first_name, :last_name, :city, :state, :about, :image, adventures_attributes: [:id, :title, :description, :duedate, :creator, :priority, :completed, :image, :_destroy])
 end
end

app/views/users/_form.html.erb
<%= form_for(@user.adventures) do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duedate %><br>
    <%= f.date_select :duedate %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_images.html.erb
<div class="form-group fileinputs2"> <!-- Upload Images Options -->
  <form role="form" class="form-group user-picture" id="user-picture" action="/users/show/addUserPicture" enctype="multipart/form-data" accept-charset="UTF-8" method="post">
  <p>Add an Image Options: (select one)</p>
  <label><input id="rdb3" type="radio" name="image_cb2" value="3" />Upload Image Using a URL</label>
  <label><input id="rdb4" type="radio" name="image_cb2" value="4" />Upload Image from Local Drive</label>

  <div id="image_3" class="field toHide">
      Enter URL to Upload Your Image: <%= text_field_tag 'image_url' %>
  </div>
  <div id="image_4" class="form-group toHide">
    <label for="adventure_image">Upload an Image From Your PC:</label><input type="file" class="file" name="adventure[image]" id="adventure_image" />
  </div>

  <div class="actions">
    <input class="btn btn-info" type="submit" name="commit" value="Add"/>
  </div>

   <%= link_to "Cancel", users_show_cancel_path, class: "block", id: "cancel", remote: true %>
 </div> <!-- Upload Image End -->

app/views/users/_login_modal.html.erb
<div class="modal hide fade in" id="login">

  <div class="modal-header">

    <button class="close" data-dismiss="modal">x</button>

    <h2>Sign in</h2>

  </div>

  <div class="modal-body">

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <% if devise_mapping.rememberable? -%>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end -%>

      <div class="actions">
        <%= f.submit "Log in" %>
      </div>
    <% end %>

  </div>

  <div class="modal-footer">

    <!-- <%= render "devise/shared/links" %> -->

  </div>

</div>

app/views/users/_sign_up_modal.html.erb
<div class="modal hide fade in" id="login">

  <div class="modal-header">

    <button class="close" data-dismiss="modal">x</button>

    <h2>Sign up</h2>

  </div>

  <div class="modal-body">

    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>

      <div class="field">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name, autofocus: true %>
    </div>

    <div class="field">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :city %><br />
        <%= f.text_field :city %>
    </div>
    <div class="field">
        <%= f.label :state %><br />
        <%= f.text_field :state %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
  <% end %>
  </div>

    <div class="modal-footer">
      <%= render "devise/shared/links" %>
    </div>

</div>

app/views/users/followPage.html.erb
<div class="container martop">
  <div class="row">
    <div class="col-md-6">
      <div class="col-md-12 my_box_center_mod">
        <h3>Currently Following (<%= @followers.length %>)</h3>
        <% if @followers != [] %> <!-- Can someone please explain this to me?-->
          <% @followers.each do |f| %>
            <div class="user-box inline">
              <div class="user-pic">
                <a href="/users/<%= f.id %>">
                  <% if f.image.blank? %>
                    <img src="/system/person-placeholder.jpg" class="follow-image"/>
                  <% else %>
                    <%= image_tag f.image.url(:med), class: 'follow-image' %>
                  <% end %>
                </a>
              <a href="/users/<%= f.id %>"><p class="text-center"><%= f.first_name %> <%= f.last_name %></a></p>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="text-center">You aren't currently following any users.</p>
        <% end %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="col-md-12 my_box_center_mod">
        <h3>Your Followers (<%= @yourFollowers.length %>)</h3>
        <% if @yourFollowers != [] %> <!-- Can someone please explain this to me?-->
          <% @yourFollowers.each do |f| %>
            <div class="user-box inline">
              <div class="user-pic">
                <a href="/users/<%= f.id %>">
                  <% if f.image.blank? %>
                    <img src="/system/person-placeholder.jpg" class="follow-image"/>
                  <% else %>
                    <%= image_tag f.image.url(:med), class: 'follow-image' %>
                  <% end %>
                </a>
              <a href="/users/<%= f.id %>"><p class="text-center"><%= f.first_name %> <%= f.last_name %></a></p>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="text-center">No users are currently following you.</p>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<h1 class="text-center martop">All Users</h1>
<div class="container">
  <div class="row">
    <% @users.each do |f| %>
      <div class="user-box col-md-3 text-center">
        <div class="user-pic">
          <a href="/users/<%= f.id %>" class="transparent">
            <% if f.image.blank? %>
              <img src="/system/person-placeholder.jpg" class="user-search-image"/>
            <% else %>
              <%= image_tag f.image.url(:large), class: "user-search-image" %>
            <% end %>
          </a>
        <a href="/users/<%= f.id %>"><h4><%= f.first_name %> <%= f.last_name %></a></h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container text-right"><h4><%= will_paginate @users %></h4></div>

app/views/users/search_users.html.erb
<div class="container my_box_center_for_search_mod text-center">
<!--Search Adventure -->

  <h3>Search Users</h3>
  <form class="form-group" action='/users/search_users' method='get'>
    <input class="form-control half-width center-block" type="text" name="creator" id="user" /><br>
    <a href='/users/all'>All Users</a>
    <div class="actions">
      <input class="btn btn-buckets marhalftop" type="submit" value="Search"/>
    </div>
  </form>
</div>


<div class="container">
  <% if !@user.nil? %>
    <% if !@user.empty? %>
      <h3 class="text-center">Users found:</h3>

      <div class="row">
        <% @user.each do |f| %>
          <div class="user-box col-md-3 text-center">
            <div class="user-pic">
              <a href="/users/<%= f.id %>" class="transparent">
                <% if f.image.blank? %>
                  <img src="/system/person-placeholder.jpg" class="user-search-image"/>
                <% else %>
                  <%= image_tag f.image.url(:large), class: "user-search-image" %>
                <% end %>
              </a>
            <a href="/users/<%= f.id %>"><h4><%= f.first_name %> <%= f.last_name %></a></h4>
            </div>
          </div>
        <% end %>
        <div class="container text-right"><h4><%= will_paginate @user %></h4></div>

      </div>

    <% else %>
      <h4 class="text-center martop main-font">No Users Found</h4>

    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<!--Profile Home Page -->

<!--User Profile Name and Photo-->
<div class ="container martop">
    <div class="row-fluid">
        <div class="col-md-6 light-background well box">

            <div class="row">
            <!--Begin Profile Image-->
                <div class="col-xs-3">
                    <div class="user_image_placeholder">
                        <% if @user.image.blank? %>
                            <img class= "responsive" src="/system/person-placeholder.jpg"/> <!--default photo-->
                        <% else %>
                        <%= image_tag @user.image.url(:large), class:"user_image_placeholder  border-color" %>
                        <% end %>
                            <!--Edit Profile Picture Link-->
                            <% if current_user == @user %>
                                <p class="pointer dark-font small-font" id="user_pic">Edit Picture</p>
                            <% end %>
                    </div>
                </div> <!--End Profile Image-->

                <!--Follow Button-->
                <div class="col-xs-offset-6 col-xs-1">
                    <% if user_signed_in? %>
                        <% if @user != current_user && !current_user.follows?(@user) %>
                            <div class="follow"><a href="/users/<%= @user.id %>/followUser" class="button btn btn-buckets main-background light-font">Follow</a>
                            </div>
                        <% elsif @user != current_user && current_user.follows?(@user) %>
                            <div class="unfollow"><a href="/users/<%= @user.id %>/unfollowUser" class="button btn btn-buckets main-background light-font">Unfollow</a>
                            </div>
                        <% end %>
                    <% end %>
                </div> <!--End Follow Buttons-->
            </div><!--End of Profile Box Column-->

            <!-- Upload Profile Image Options -->
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group fileinputs2">
                        <form role="form" class="form-group user-picture" id="user-picture" action="/users/show/addUserPicture" enctype="multipart/form-data" accept-charset="UTF-8" method="post">
                            <div class="radio-buttons">
                                <p class="muted">Add an Image Options: (select one)</p>
                                <label class="muted padright"><input id="rdb3" type="radio" name="image_cb2" value="3" />Upload Image Using a URL</label>
                                <div id="image_3" class="field toHide2 image-url">Enter URL to Upload Your Image: <%= text_field_tag 'image_url2' %>
                            </div>
                                <label class="muted"><input id="rdb4" type="radio" name="image_cb2" value="4" />Upload Image from Local Drive</label>
                            </div><!--end of radio buttons-->

                            <div id="image_4" class="form-group toHide2 image-file">
                                <label for="adventure_image2">Upload an Image From Your PC:</label><input type="file" class="file" name="user_image" id="adventure_image2" />
                            </div>
                            <div class="actions profile-pic-submit">
                                <input class="btn btn-buckets" type="submit" name="commit2" value="Add"/>                   <p class="cancel pointer btn btn-buckets" style="display: inline;" id="cancel">Cancel</p>
                            </div>
                        </form>
                    </div> <!-- End of Upload Profile Image Form-->
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <!-- Name, City, State Display -->
                    <h3 class="main-font lg-font"><%= @user.first_name %> <%= @user.last_name %></h3>
                    <p class="dark-font italic"><%= @user.city %>, <%= @user.state %></p>
                </div>
            </div>
        </div><!--End of profile box column class-->

        <!--Begin Featured Bucket-->
        <div class="col-md-offset-1 col-md-5 well box main-background">
                <div><h3 class="header text-center light-font lg-font">Featured Bucket</h3></div>
                <div class="text-center" id="result"></div>
                <div class="martop" id="bucket_image"></div>
                <h4 class="title dark-font" id="bucket_title"></h4>
        </div>
        <!--End of Featured Bucket-->

    </div><!-- End of Profile Box Row-->

    <!--About Me-->
    <div class="row marbot">
        <div class="col-md-12">
            <% if @user == current_user %>
                <h3>About Me</h3>
            <% else %>
                <h3>About <%= @user.first_name %> <%= @user.last_name %></h3>
            <% end %>
                <p class="muted"><%= @user.about %></p>
        </div>
    </div><!--End of About-->

</div> <!--End of Profile and About Container-->


<!--Bucket List-->
<div class="well light-background">
    <h3 class="lg-font main-font text-center marbot nomartop">My Buckets:</h3>
    <% if @user.adventures.any? %>
    <% @user.adventures.each do |adventure| %>
    <div class="container-fluid">
        <div class="row">
            <div class="bucket col-md-3 col-sm-4 col-xs-12">
                <div class="tip">
                    <div class="handle"></div>
                    <div class="img_tip">
                    <%= link_to image_tag(adventure.image.url(:large)), adventure, :class => "image_tip" %>
                    </div>
                </div>
                <h4><%= adventure.title.upcase %></h4>
                <h5><%= adventure.creator %></h5>
                <% if @user == current_user %>
                <h5><%= link_to 'Show', adventure %> | <%= link_to 'Edit', edit_adventure_path(adventure) %> | <%= link_to 'Dump', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></h5>
                <% end %>
            </div> <!--End of Bucket Loop Row-->
        <% end %>
        <% else %>
          <p class="text-center">Adventures Coming Soon!</p>
        </div> <!--End of Bucket Loop Row-->
    <% end %>
    </div> <!--End of Bucket Container-->
</div>



<!--Begin Add Adventure -->
<div id="add-adventure" class="container-fluid">
    <div class="row">
        <div class="col-sm-offset-2 col-sm-8 col-xs-12">
            <% if @user == current_user %>
            <h3 class="lg-font main-font martop">Add New Bucket</h3>
                <form role="form" class="form-group new_adventure" id="new_adventure" action="/users/<%= @user.id %>/add_adventure" enctype="multipart/form-data" accept-charset="UTF-8" method="post">
                    <div class="form-group">
                        <label for="adventure_title">Bucket Name</label>
                        <input class="form-control" type="text" name="adventure[title]" id="adventure_title" pla="Adventure Title"/>
                    </div>
                    <div class="form-group">
                            <label for="adventure_description">Description</label>
                            <textarea class="form-control" rows="3" name="adventure[description]" id="adventure_description"></textarea>
                    </div>
                    <div class="form-group">
                            <label for="adventure_duedate">Due Date</label>
                            <input class="form-control" type="date" name="adventure[duedate]" id="adventure_duedate" />
                    </div>
                    <div class="form-group">
                            <label for="adventure_priority">Priority</label>
                            <input class="form-control" type="number" name="adventure[priority]" min="1" max="5" id="adventure_priority"/>
                    </div>

                  <!--Upload Adventure Image Begin -->
                    <div class="form-group fileinputs">
                          <!-- Upload Images Options -->
                          <p><strong>Add an Image Options: </strong><span class="main-font">(select one)</span></p>
                          <label class="muted padright"><input id="rdb1" type="radio" name="image_cb" value="1" />Upload Image Using a URL</label>
                          <label class="muted"><input id="rdb2" type="radio" name="image_cb" value="2" />Upload Image from Local Drive</label>
                          <div id="image_1" class="field toHide muted">Enter URL to Upload Your Image: <%= text_field_tag 'image_url' %>
                          </div>
                          <div id="image_2" class="muted form-group toHide">
                            <label class-"muted" for="adventure_image">Upload an Image From Your PC:</label><input type="file" class="file" name="adventure[image]" id="adventure_image" />
                          </div>
                    </div><!-- Upload Image End -->

                    <div class="checkbox">
                      <label for="adventure_completed"><input class="checkbox" type="checkbox" name="adventure[completed]" id="adventure_completed" value="Done"><strong>Done?</strong></label>
                   </div>

                      <div class="form-group actions">
                        <input class="btn btn-buckets" type="submit" name="commit" value="Add"/>
                      </div>
                </form>
            <% end %>
        </div><!--End of Column-->
    </div><!--End of Row-->
</div><!--End of Container-->
<div class="user_id"><p><%= @user.id %></p></div>
<!-- End Add Adventure  -->
<script src="../assets/get_random_adventure.js"></script>