config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
    root 'public#bucket_list_index'

    match('/users/:id/get_random_adventure', {:via => :get, :to => 'users#get_random_adventure'})
    match('/adventures/get_random_adventure', {:via => :get, :to => 'adventures#get_random_adventure'})
    match('/adventures/:id/add_comment' , {:via => :post, :to => 'adventures#add_comment'})
    match('/adventures/:id/add_tag' , {:via => :post, :to => 'adventures#add_tag'})
    match('/users/search_users' , {:via => :get, :to => 'users#search_users'})
    match('users/show' , {:via => :get, :to => 'users#show'})
    match('users/show/newPic' , {:via => :get, :to => 'users#newPic'})
    match('users/show/cancel' , {:via => :get, :to => 'users#cancel'})
    match('users/show/addUserPicture' , {:via => :post, :to => 'users#addUserPicture'})
    match('users/:id/followUser' , {:via => :get, :to => 'users#followUser'})
    match('users/:id/unfollowUser' , {:via => :get, :to => 'users#unfollowUser'})
    match('users/show/followPage' , {:via => :get, :to => 'users#followPage'})
    match('users/all', {:via => :get, :to => 'users#index'})
    match('users/:id' , {:via => :get, :to => 'users#view_profile'})
    match('/users/:id/add_adventure' , {:via => :post, :to => 'users#add_adventure'})
    match('/adventures/search_adventures' , {:via => :get, :to => 'adventures#search_adventures'})

    resources :migrations
    resources :pictures
    resources :adventures

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Poppins:400,300' rel='stylesheet' type='text/css'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>


    <title> Bucketlist </title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script>
    $(document).ready(function() {

      $("#owl-demo").owlCarousel();

    });
    </script>
  </head>
  <body>

  <div class="mainContent container-fluid">
  <!-- Navigation  -->
    <% if user_signed_in? %>
  <div class="container-fluid my_need_a_margin">
    <nav class="navbar navbar-default navbar-fixed-top my_navbar">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="my_navbar_image">
            <% if !current_user.image.blank? %>
              <%= link_to image_tag(current_user.image.url(:small)), root_path, class:"image_tip pro-thumb" %>
            <% else %>
              <a class="pro-thumb image_tip" href="/"><img src="/system/person-placeholder.jpg"/></a>
            <% end %>
              <%= link_to "Hi " + current_user.first_name, users_show_path, class:"nav-custom" %>
          </span>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <!--Right side of the nav bar  -->
          <ul class="nav navbar-nav navbar-right">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle dark-font" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Your Profile', users_show_path %></li>
                  <li><%= link_to 'Edit Your Profile', edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle dark-font" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/users/show/followPage">Friends</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Search Users", users_search_users_path %></li>
                  <li><a href="/users/all">View All Users</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle dark-font" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Adventures<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Search Adventures!", adventures_search_adventures_path %></li>
                  <li><a href="/adventures">View All Adventures!</a></li>
                </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
  <!-- End navigation for signed-in users -->


        <% else %>

  <!-- Begin navigation for non-signed in users -->
      <div class="container-fluid need_a_margin">
        <nav class="navbar navbar-default navbar-fixed-top my_navbar">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <span class="my_navbar_image">
                  <%= link_to image_tag("paintbucket.png"),root_path, class: "pro-thumb" %>
              </span>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <!--Right side of the nav bar  -->
              <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle dark-font" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Adventures<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Search Adventures!", adventures_search_adventures_path %></li>
                        <li><a href="/adventures">View All Adventures!</a></li>
                      </ul>
                  </li>
                  <li>
                      <a href="/users/sign_in" class="nav-custom">Log In</a>
                  </li>
                  <li>
                       <a href="/users/sign_up" class="nav-custom">Sign Up</a>
                  </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div>
        </nav>
      </div>

      <% end %>
  </div>


<%= yield %>



  </body>
</html>